services:
  erpc:
    image: "ghcr.io/succinctlabs/erpc:0.0.19"
    entrypoint: "/entry.sh"
    ports:
      - "9545:9545"
    environment:
      RPC_1: "${RPC_1}"
      RPC_2: "${RPC_2}"
      RPC_3: "${RPC_3}"
      RPC_4: "${RPC_4}"
      RPC_5: "${RPC_5}"
      NO_CATCH_ALL: "1"
    volumes:
      - "./entrypoints/erpc.sh:/entry.sh:ro"
    depends_on:
      - "redis"

  redis:
    image: "redis:7.4"
    entrypoint: "/entry.sh"
    volumes:
      - "./entrypoints/redis-generate.sh:/entry.sh:ro"
      - "./data:/data"
